language: php

jobs:
  fast_finish: true
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - php: '7.4'
      name: 'Prefer lowest'
      install:
        - composer update --no-interaction --prefer-lowest
    - php: 'nightly'
      install:
        - composer update --no-interaction --ignore-platform-reqs
  allow_failures:
    - php: 'nightly'

env:
  global:
    - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.cache/composer/files

install:
  composer update --no-interaction

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit
